#!/bin/dash

if ! test -d ".mygive";then
    echo "tmygive-summary: mygive directory .mygive not found"
    exit 1
fi

if test -z "$(ls -A .mygive/ 2>/dev/null)";then
    echo "no assignments"
    exit 1
fi

for ass in .mygive/*; do

    if [ -d "$ass" ];then
        ass_basename=$(basename "$ass")
        student_count=$(ls -1d "$ass"/* 2>/dev/null | wc -l)
        student_count=$((student_count-1))
        echo "assignment $ass_basename: submissions from $student_count students"
    fi
done