#!/bin/dash

for ass in .mygive/*; do

    if [ -d "$ass" ];then
        ass_basename=$(basename "$ass")
        student_count=$(ls -1d "$ass"/* 2>/dev/null | wc -l)
        student_count=$((student_count-1))
        echo "assignment $ass_basename: submissions from $student_count students"
    fi
done