#!/bin/dash

if [ $# -ne 2 ]; then
    echo "usage: mygive-test <assignment> <filename>" 1>&2
    exit 1
fi  

ass_name="$1"
program_file="$2"

arguments_regex="^[a-zA-Z0-9._ \-]*$"

if ! test -d .mygive/"$ass_name"; then
    echo "mygive-test: assignment $ass_name not found" 1>&2
    exit 1
fi

# check if assignment name is valid
if [ "$(echo "$ass_name" | grep -Ec '^[a-z][a-zA-Z0-9_]*$')" -ne 1 ]; then
    echo "mygive-test: invalid assignment: $ass_name" 1>&2
    exit 1
fi

if ! test -f "$program_file"; then
    echo "mygive-test: $program_file not found" 1>&2
    exit 1
fi

passed_tests=0
failed_tests=0

for test_file in .mygive/$ass_name/tests/*; do
   test_dir=$(basename $test_file | cut -d'.' -f1)
   mkdir -p "$test_dir"
   tar -xzf "$test_file" -C "$test_dir"

   tmp_list=$(mktemp)
   find "$test_dir" -mindepth 1 -type d | sort > "$tmp_list"

   while read -r file_dir; do
        if find "$file_dir" -type f -name "*marks*" | grep -q .;then
            # echo "$file_dir"
            continue
        fi
        file_name=$(basename $file_dir)
        arguments=""
        stdin=""
        stdout=""
        options=""
        exit_status=0
        stderr=""

        result_stdout_file=$(mktemp)
        result_stderr_file=$(mktemp)
        expected_stdout_file=$(mktemp)
        expected_stderr_file=$(mktemp)

         if [ -f "./$file_dir/exit_status" ];then
            exit_status=$(cat "./$file_dir/exit_status")
        fi
        
        if [ -f "./$file_dir/arguments" ];then
            arguments=$(cat "./$file_dir/arguments")
            if ! echo "$arguments" | grep -Eq "$arguments_regex";then
                echo "mygive-test: invalid arguments: $arguments" 1>&2
                exit "$exit_status"
            fi
        fi

        if [ -f "./$file_dir/stdin" ];then
            stdin=$(cat "./$file_dir/stdin")
        fi

        if [ -f "./$file_dir/options" ];then
            options=$(cat "./$file_dir/options")
        fi

        # echo "arguments: $arguments"
        # echo "stdin: $stdin"
        # echo "stdout: $stdout"
        # echo "stderr: $stderr"

        if [ -z "$stdin" ];then
            ./"$program_file" $arguments > "$result_stdout_file" 2> "$result_stderr_file"
        else
            echo "$stdin" | ./"$program_file" $arguments > "$result_stdout_file" 2> "$result_stderr_file"
        fi

        if [ -f "./$file_dir/stdout" ];then
            cp "./$file_dir/stdout" "$expected_stdout_file"
        else
            : > "$expected_stdout_file"
        fi

        tmp_file=$(mktemp)

        if echo "$options" | grep -q "b"; then
            sed -i '' "/^$/d" "$result_stdout_file"
            sed -i '' "/^$/d" "$expected_stdout_file"
        fi

        if echo "$options" | grep -q "c"; then
            tr '[:upper:]' '[:lower:]' < "$result_stdout_file" > "$tmp_file"
            mv "$tmp_file" "$result_stdout_file"
            tr '[:upper:]' '[:lower:]' < "$expected_stdout_file" > "$tmp_file"
            mv "$tmp_file" "$expected_stdout_file"
        fi

        if echo "$options" | grep -q "w"; then
           tr -d ' \t' < "$result_stdout_file" > "$tmp_file"
            mv "$tmp_file" "$result_stdout_file"
            tr -d ' \t' < "$expected_stdout_file" > "$tmp_file"
            mv "$tmp_file" "$expected_stdout_file"
        fi

        if echo "$options" | grep -q "d"; then
            sed -i '' 's/[^0-9\n]//g' "$result_stdout_file"
            sed -i '' 's/[^0-9\n]//g' "$expected_stdout_file"
        fi
            #   echo "Expected: "
            #     cat "$expected_stdout_file"

            #     echo "Result: "
            #     cat "$result_stdout_file"

        cmp -s "$expected_stdout_file" "$result_stdout_file"

        if [ $? -eq 0 ];then
            echo "* Test $file_name passed."
            passed_tests=$((passed_tests+1))
        else
            echo "* Test $file_name failed."
            failed_tests=$((failed_tests+1))

            result_size=$(stat -f"%z" "$result_stdout_file")
            expected_result_size=$(stat -f"%z" "$expected_stdout_file")

            result_char_result=$(tail -c 1 "$result_stdout_file")
            expected_char_result=$(tail -c 1 "$expected_stdout_file")
            #result_size=$(stat -c%s "$result_stdout_file")
            #expected_result_size=$(stat -c%zs "./$file_dir/stdin")

            if [ ! -s "$expected_stdout_file" ] && [ -s "$result_stdout_file" ];then
                echo "--- No stdout expected, these $result_size bytes produced:"
                cat "$result_stdout_file"
                echo ""
            elif [ ! -s "$result_stdout_file" ] && [ -s "$expected_stdout_file" ];then
                echo "--- No stdout produced, these $expected_result_size bytes expected:"
                cat "$expected_stdout_file"
                echo ""
            elif [ $(($result_size - $expected_result_size)) -eq 1 ] && [ "$result_char_result" = "" ];then
                new_expected_file=$(mktemp)
                cat "$expected_stdout_file" > "$new_expected_file"
                printf "\n" >> "$new_expected_file"
                if cmp -s "$new_expected_file" "$result_stdout_file";then
                    echo "Extra newline at end of stdout"
                else
                    echo "--- Incorrect stdout of $result_size bytes:"
                    cat "$result_stdout_file"
                    echo ""
                    
                    echo "--- Correct stdout is these $expected_result_size bytes:"
                    cat "$expected_stdout_file"
                    echo ""
                fi
            elif [ $(($expected_result_size - $result_size)) -eq 1 ] && [ "$expected_char_result" = "" ];then
                new_result_file=$(mktemp)
                cat "$result_stdout_file" > "$new_result_file"
                printf "\n" >> "$new_result_file"
                if cmp -s "$new_result_file" "$expected_stdout_file";then
                    echo "Missing newline at end of stdout"
                else
                    echo "--- Incorrect stdout of $result_size bytes:"
                    cat "$result_stdout_file"
                    echo ""
                    
                    echo "--- Correct stdout is these $expected_result_size bytes:"
                    cat "$expected_stdout_file"
                    echo ""
                fi
             else
                echo "--- Incorrect stdout of $result_size bytes:"
                cat "$result_stdout_file"
                echo ""
                            
                echo "--- Correct stdout is these $expected_result_size bytes:"
                cat "$expected_stdout_file"
                echo ""
            fi
        fi
   done < "$tmp_list"
#    rm -rf "$test_dir"
done

echo "** $passed_tests tests passed, $failed_tests tests failed"

