#!/bin/dash

ass_name=$1
test_files=$2

ass_regex="^[a-z][a-zA-Z0-9_]*$"
test_regex="^[a-zA-Z0-9._/\-]+$"

if test $# != 2; then
    echo "usage: mygive-add <assignment> <tests>" >&2
    exit 1
fi 

if ! echo "$ass_name" | grep -Eq "$ass_regex";then
    echo "mygive-add: invalid assignment: $ass_name" 1>&2
    exit 1
fi

if ! echo "$test_files" | grep -Eq "$test_regex";then
    echo "test file is invalid" 1>&2
    exit 1
fi

if [ ! -d ".mygive" ];then
    mkdir .mygive
    echo "directory .mygive created"
fi

if ! test -f "$test_files";then
    echo "mygive-add: $test_files: No such file or directory" 1>&2
    exit 1
fi

if [ ! -d ".mygive/$ass_name" ];then
    mkdir ".mygive/$ass_name"
    echo "assignment $ass_name created"
else 
    echo "mygive-add: assignment $ass_name already exists" 1>&2
    exit 1
fi

if [ ! -d ".mygive/$ass_name/tests" ];then
    mkdir ".mygive/$ass_name/tests"
fi

cp "$test_files" ".mygive/$ass_name/tests"